#!/usr/bin/env bash
set -eo pipefail; [[ $DOKKU_TRACE ]] && set -x
source "$(dirname "$0")/config"

if [[ ! -d $VOLUMES_ROOT ]]; then
  mkdir -p "$VOLUMES_ROOT"
  chown dokku:dokku "$VOLUMES_ROOT"
fi
