#!/usr/bin/env bash
set -eo pipefail; [[ $DOKKU_TRACE ]] && set -x

PLUGIN_BASE_PATH="$PLUGIN_PATH"
if [[ -n $DOKKU_API_VERSION ]]; then
  PLUGIN_BASE_PATH="$PLUGIN_ENABLED_PATH"
fi
source "$PLUGIN_BASE_PATH/common/functions"
source "$(dirname "$0")/config"

APP="$1"; APP_VOLUME="$VOLUMES_ROOT/$APP"; IMAGE="dokku/$APP"
VOLUMES=$(docker inspect --format='{{range $volume, $value := .Config.Volumes}}{{$volume}}{{"\n"}}{{end}}' "$IMAGE")

for VOLUME in $VOLUMES; do
  # Add slashes before spaces
  VOLUME=$(echo $VOLUME | awk '{gsub(/ /,"\\ ")}8')
  VOLUME_PATH="$APP_VOLUME$VOLUME"
  VOLUME_DIR=$(dirname "$VOLUME_PATH")
  if [[ -e $VOLUME_PATH ]]; then
    continue
  fi
  echo "Prepearing Docker volume: ${VOLUME}"
  mkdir -p "$VOLUME_DIR"
  echo "Copying files from container ($VOLUME) to host ($VOLUME_PATH)"
  # Copy container files into host folder
  docker run --rm -v "$VOLUME_DIR:/target" "$IMAGE" bash -c "cp -a $VOLUME /target"
  # Add docker volume options
  echo "Adding docker options: $APP run,deploy -v $VOLUME_PATH:$VOLUME"
  dokku docker-options:add "$APP" run,deploy "-v $VOLUME_PATH:$VOLUME"
done

exit 0
