#!/usr/bin/env bash
set -eo pipefail; [[ $DOKKU_TRACE ]] && set -x

PLUGIN_BASE_PATH="$PLUGIN_PATH"
if [[ -n $DOKKU_API_VERSION ]]; then
  PLUGIN_BASE_PATH="$PLUGIN_ENABLED_PATH"
fi
source "$PLUGIN_BASE_PATH/common/functions"
source "$(dirname "$0")/config"

APP="$1"; APP_VOLUME="$VOLUMES_ROOT/$APP"
if [[ -e $APP_VOLUME ]]; then
  docker run --rm -v "$VOLUMES_ROOT:/volumes" busybox chmod 777 -R /volumes
  rm -rf "$APP_VOLUME"
fi
exit 0
